// <auto-generated />
using System;
using DotnetBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotnetBackend.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220327190211_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DotnetBackend.Core.Entities.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("LGAId")
                        .HasColumnType("bigint");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("LGAId");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DotnetBackend.Core.Entities.LGA", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StateId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("LGAs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8151), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 1",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8194), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 2",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8197), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 3",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8199), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 4",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8201), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 5",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8205), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 6",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8207), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 7",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8210), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 8",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 9L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8212), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 9",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8215), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 10",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 11L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8218), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 11",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 12L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8220), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 12",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 13L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8223), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 13",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 14L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8225), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 14",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 15L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8227), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 15",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 16L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8230), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 1",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 17L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8232), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 2",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 18L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8235), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 3",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 19L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8238), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 4",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 20L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8240), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 5",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 21L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8242), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 6",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 22L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8244), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 7",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 23L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8246), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 8",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 24L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8249), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 9",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 25L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8251), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 10",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 26L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8322), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 11",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 27L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8325), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 12",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 28L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8327), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 13",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 29L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8330), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 14",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 30L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8332), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 15",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 31L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8334), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 1",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 32L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8336), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 2",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 33L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8339), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 3",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 34L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8342), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 4",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 35L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8344), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 5",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 36L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8346), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 6",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 37L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8349), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 7",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 38L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8351), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 8",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 39L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8353), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 9",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 40L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8356), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 10",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 41L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8358), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 11",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 42L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8360), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 12",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 43L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8363), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 13",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 44L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8365), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 14",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 45L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8367), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 15",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 46L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8369), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 1",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 47L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8372), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 2",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 48L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8374), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 3",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 49L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8376), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 4",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 50L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8379), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 5",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 51L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8381), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 6",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 52L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8383), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 7",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 53L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8385), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 8",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 54L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8387), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 9",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 55L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8390), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 10",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 56L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8392), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 11",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 57L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8394), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 12",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 58L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8397), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 13",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 59L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8399), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 14",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 60L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8401), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 15",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 61L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8404), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 1",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 62L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8406), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 2",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 63L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8408), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 3",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 64L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8410), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 4",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 65L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8412), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 5",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 66L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8416), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 6",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 67L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8418), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 7",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 68L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8420), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 8",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 69L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8423), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 9",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 70L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8425), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 10",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 71L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8427), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 11",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 72L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8429), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 12",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 73L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8432), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 13",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 74L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8434), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 14",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 75L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8436), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 15",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 76L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8438), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 1",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 77L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8441), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 2",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 78L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8443), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 3",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 79L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8445), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 4",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 80L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8447), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 5",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 81L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8449), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 6",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 82L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8452), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 7",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 83L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8506), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 8",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 84L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8509), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 9",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 85L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8511), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 10",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 86L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8513), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 11",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 87L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8515), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 12",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 88L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8518), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 13",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 89L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8520), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 14",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 90L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8522), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 15",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 91L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8524), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 1",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 92L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8526), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 2",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 93L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8529), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 3",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 94L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8531), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 4",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 95L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8533), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 5",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 96L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8535), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 6",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 97L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8537), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 7",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 98L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8540), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 8",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 99L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8542), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 9",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 100L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8544), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 10",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 101L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8546), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 11",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 102L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8549), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 12",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 103L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8551), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 13",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 104L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8553), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 14",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 105L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8555), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 15",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 106L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8558), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 1",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 107L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8560), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 2",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 108L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8562), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 3",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 109L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8564), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 4",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 110L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8567), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 5",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 111L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8569), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 6",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 112L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8571), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 7",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 113L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8573), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 8",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 114L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8575), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 9",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 115L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8578), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 10",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 116L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8580), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 11",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 117L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8582), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 12",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 118L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8584), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 13",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 119L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8587), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 14",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 120L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(8589), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 15",
                            StateId = 8L
                        });
                });

            modelBuilder.Entity("DotnetBackend.Core.Entities.OTP", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("CustomerId");

                    b.ToTable("OTPs");
                });

            modelBuilder.Entity("DotnetBackend.Core.Entities.State", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(7905), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Abia State"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(7927), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Lagos State"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(7929), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Kaduna State"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(7930), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Sokoto State"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(7931), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Ogun State"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(7933), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Taraba State"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(7935), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Imo State"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 27, 20, 2, 10, 442, DateTimeKind.Unspecified).AddTicks(7936), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Edo State"
                        });
                });

            modelBuilder.Entity("DotnetBackend.Core.Entities.Customer", b =>
                {
                    b.HasOne("DotnetBackend.Core.Entities.LGA", "LGA")
                        .WithMany()
                        .HasForeignKey("LGAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LGA");
                });

            modelBuilder.Entity("DotnetBackend.Core.Entities.LGA", b =>
                {
                    b.HasOne("DotnetBackend.Core.Entities.State", "State")
                        .WithMany("LGAs")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("DotnetBackend.Core.Entities.OTP", b =>
                {
                    b.HasOne("DotnetBackend.Core.Entities.Customer", "Customer")
                        .WithMany("OTPs")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DotnetBackend.Core.Entities.Customer", b =>
                {
                    b.Navigation("OTPs");
                });

            modelBuilder.Entity("DotnetBackend.Core.Entities.State", b =>
                {
                    b.Navigation("LGAs");
                });
#pragma warning restore 612, 618
        }
    }
}
