// <auto-generated />
using System;
using DotnetBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotnetBackend.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220328041003_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DotnetBackend.Core.Entities.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("LGAId")
                        .HasColumnType("bigint");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("LGAId");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DotnetBackend.Core.Entities.LGA", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StateId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("LGAs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3240), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 1",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3301), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 2",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3306), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 3",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3310), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 4",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3313), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 5",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3318), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 6",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3321), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 7",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3324), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 8",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 9L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3328), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 9",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3333), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 10",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 11L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3336), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 11",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 12L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3340), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 12",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 13L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3343), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 13",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 14L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3347), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 14",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 15L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3351), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 15",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 16L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3354), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 1",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 17L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3358), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 2",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 18L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3363), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 3",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 19L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3366), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 4",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 20L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3370), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 5",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 21L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3374), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 6",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 22L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3378), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 7",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 23L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3381), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 8",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 24L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3385), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 9",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 25L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3388), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 10",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 26L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3391), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 11",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 27L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3395), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 12",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 28L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3399), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 13",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 29L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3402), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 14",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 30L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3406), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 15",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 31L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3409), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 1",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 32L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3413), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 2",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 33L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3416), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 3",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 34L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3421), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 4",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 35L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3424), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 5",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 36L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3435), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 6",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 37L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3445), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 7",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 38L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3454), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 8",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 39L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3464), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 9",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 40L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3471), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 10",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 41L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3475), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 11",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 42L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3478), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 12",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 43L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3481), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 13",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 44L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3484), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 14",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 45L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3487), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 15",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 46L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3491), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 1",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 47L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3494), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 2",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 48L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3497), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 3",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 49L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3500), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 4",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 50L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3503), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 5",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 51L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3506), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 6",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 52L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3509), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 7",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 53L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3512), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 8",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 54L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3515), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 9",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 55L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3519), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 10",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 56L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3522), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 11",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 57L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3526), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 12",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 58L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3530), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 13",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 59L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3533), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 14",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 60L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3547), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 15",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 61L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3552), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 1",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 62L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3555), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 2",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 63L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3558), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 3",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 64L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3561), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 4",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 65L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3564), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 5",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 66L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3570), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 6",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 67L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3573), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 7",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 68L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3577), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 8",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 69L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3580), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 9",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 70L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3583), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 10",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 71L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3586), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 11",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 72L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3589), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 12",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 73L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3593), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 13",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 74L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3596), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 14",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 75L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3599), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 15",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 76L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3603), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 1",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 77L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3607), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 2",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 78L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3610), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 3",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 79L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3613), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 4",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 80L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3616), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 5",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 81L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3619), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 6",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 82L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3622), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 7",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 83L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3625), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 8",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 84L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3628), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 9",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 85L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3631), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 10",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 86L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3634), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 11",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 87L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3637), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 12",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 88L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3640), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 13",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 89L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3643), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 14",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 90L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3646), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 15",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 91L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3650), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 1",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 92L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3653), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 2",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 93L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3656), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 3",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 94L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3660), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 4",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 95L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3663), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 5",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 96L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3667), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 6",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 97L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3670), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 7",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 98L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3673), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 8",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 99L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3677), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 9",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 100L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3680), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 10",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 101L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3684), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 11",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 102L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3687), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 12",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 103L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3690), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 13",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 104L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3694), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 14",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 105L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3697), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 15",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 106L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3700), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 1",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 107L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3704), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 2",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 108L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3707), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 3",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 109L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3711), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 4",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 110L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3714), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 5",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 111L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3717), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 6",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 112L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3720), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 7",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 113L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3724), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 8",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 114L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3727), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 9",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 115L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3730), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 10",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 116L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3734), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 11",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 117L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3738), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 12",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 118L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3742), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 13",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 119L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3745), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 14",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 120L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(3748), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 15",
                            StateId = 8L
                        });
                });

            modelBuilder.Entity("DotnetBackend.Core.Entities.OTP", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("CustomerId");

                    b.ToTable("OTPs");
                });

            modelBuilder.Entity("DotnetBackend.Core.Entities.State", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(2893), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Abia State"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(2923), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Lagos State"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(2925), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Kaduna State"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(2927), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Sokoto State"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(2929), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Ogun State"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(2931), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Taraba State"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(2933), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Imo State"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 5, 10, 2, 771, DateTimeKind.Unspecified).AddTicks(2935), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Edo State"
                        });
                });

            modelBuilder.Entity("DotnetBackend.Core.Entities.Customer", b =>
                {
                    b.HasOne("DotnetBackend.Core.Entities.LGA", "LGA")
                        .WithMany()
                        .HasForeignKey("LGAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LGA");
                });

            modelBuilder.Entity("DotnetBackend.Core.Entities.LGA", b =>
                {
                    b.HasOne("DotnetBackend.Core.Entities.State", "State")
                        .WithMany("LGAs")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("DotnetBackend.Core.Entities.OTP", b =>
                {
                    b.HasOne("DotnetBackend.Core.Entities.Customer", "Customer")
                        .WithMany("OTPs")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DotnetBackend.Core.Entities.Customer", b =>
                {
                    b.Navigation("OTPs");
                });

            modelBuilder.Entity("DotnetBackend.Core.Entities.State", b =>
                {
                    b.Navigation("LGAs");
                });
#pragma warning restore 612, 618
        }
    }
}
