// <auto-generated />
using System;
using DotnetBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotnetBackend.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DotnetBackend.Core.Entities.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("LGAId")
                        .HasColumnType("bigint");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("LGAId");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DotnetBackend.Core.Entities.LGA", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StateId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("LGAs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8822), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 1",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8856), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 2",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8859), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 3",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8862), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 4",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8864), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 5",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8868), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 6",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8870), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 7",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8872), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 8",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 9L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8874), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 9",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8878), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 10",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 11L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8880), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 11",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 12L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8882), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 12",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 13L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8885), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 13",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 14L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8887), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 14",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 15L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8889), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 1 + 15",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 16L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8892), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 1",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 17L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8895), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 2",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 18L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8898), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 3",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 19L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8900), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 4",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 20L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8902), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 5",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 21L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8905), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 6",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 22L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8907), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 7",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 23L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8909), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 8",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 24L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8911), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 9",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 25L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8913), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 10",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 26L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8915), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 11",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 27L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8983), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 12",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 28L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8987), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 13",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 29L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8989), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 14",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 30L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8992), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 2 + 15",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 31L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8994), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 1",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 32L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8996), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 2",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 33L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8998), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 3",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 34L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9002), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 4",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 35L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9004), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 5",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 36L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9007), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 6",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 37L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9009), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 7",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 38L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9011), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 8",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 39L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9013), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 9",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 40L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9015), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 10",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 41L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9017), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 11",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 42L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9020), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 12",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 43L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9022), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 13",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 44L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9024), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 14",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 45L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9026), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 3 + 15",
                            StateId = 3L
                        },
                        new
                        {
                            Id = 46L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9029), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 1",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 47L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9031), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 2",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 48L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9033), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 3",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 49L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9035), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 4",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 50L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9037), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 5",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 51L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9039), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 6",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 52L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9042), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 7",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 53L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9044), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 8",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 54L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9046), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 9",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 55L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9048), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 10",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 56L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9050), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 11",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 57L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9052), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 12",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 58L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9054), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 13",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 59L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9056), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 14",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 60L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9059), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 4 + 15",
                            StateId = 4L
                        },
                        new
                        {
                            Id = 61L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9061), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 1",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 62L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9063), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 2",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 63L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9066), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 3",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 64L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9068), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 4",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 65L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9070), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 5",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 66L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9074), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 6",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 67L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9076), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 7",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 68L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9078), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 8",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 69L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9081), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 9",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 70L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9083), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 10",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 71L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9085), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 11",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 72L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9087), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 12",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 73L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9089), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 13",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 74L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9092), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 14",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 75L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9094), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 5 + 15",
                            StateId = 5L
                        },
                        new
                        {
                            Id = 76L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9096), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 1",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 77L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9098), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 2",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 78L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9100), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 3",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 79L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9103), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 4",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 80L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9105), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 5",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 81L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9107), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 6",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 82L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9109), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 7",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 83L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9112), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 8",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 84L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9114), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 9",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 85L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9168), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 10",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 86L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9171), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 11",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 87L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9174), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 12",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 88L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9176), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 13",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 89L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9178), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 14",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 90L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9180), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 6 + 15",
                            StateId = 6L
                        },
                        new
                        {
                            Id = 91L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9183), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 1",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 92L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9185), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 2",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 93L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9187), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 3",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 94L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9189), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 4",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 95L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9192), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 5",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 96L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9194), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 6",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 97L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9196), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 7",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 98L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9198), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 8",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 99L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9200), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 9",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 100L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9202), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 10",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 101L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9204), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 11",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 102L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9206), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 12",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 103L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9209), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 13",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 104L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9211), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 14",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 105L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9213), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 7 + 15",
                            StateId = 7L
                        },
                        new
                        {
                            Id = 106L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9215), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 1",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 107L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9218), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 2",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 108L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9220), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 3",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 109L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9222), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 4",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 110L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9224), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 5",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 111L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9226), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 6",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 112L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9228), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 7",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 113L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9231), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 8",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 114L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9233), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 9",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 115L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9235), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 10",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 116L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9237), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 11",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 117L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9239), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 12",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 118L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9242), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 13",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 119L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9244), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 14",
                            StateId = 8L
                        },
                        new
                        {
                            Id = 120L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(9246), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "LGA 8 + 15",
                            StateId = 8L
                        });
                });

            modelBuilder.Entity("DotnetBackend.Core.Entities.OTP", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("HashOTPCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("HashOTPCode");

                    b.ToTable("OTPs");
                });

            modelBuilder.Entity("DotnetBackend.Core.Entities.State", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8543), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Abia State"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8565), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Lagos State"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8567), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Kaduna State"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8568), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Sokoto State"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8569), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Ogun State"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8571), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Taraba State"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8572), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Imo State"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedBy = "SYSTEM",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 3, 28, 14, 18, 0, 673, DateTimeKind.Unspecified).AddTicks(8573), new TimeSpan(0, 1, 0, 0, 0)),
                            Name = "Edo State"
                        });
                });

            modelBuilder.Entity("DotnetBackend.Core.Entities.Customer", b =>
                {
                    b.HasOne("DotnetBackend.Core.Entities.LGA", "LGA")
                        .WithMany()
                        .HasForeignKey("LGAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LGA");
                });

            modelBuilder.Entity("DotnetBackend.Core.Entities.LGA", b =>
                {
                    b.HasOne("DotnetBackend.Core.Entities.State", "State")
                        .WithMany("LGAs")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("DotnetBackend.Core.Entities.OTP", b =>
                {
                    b.HasOne("DotnetBackend.Core.Entities.Customer", "Customer")
                        .WithMany("OTPs")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DotnetBackend.Core.Entities.Customer", b =>
                {
                    b.Navigation("OTPs");
                });

            modelBuilder.Entity("DotnetBackend.Core.Entities.State", b =>
                {
                    b.Navigation("LGAs");
                });
#pragma warning restore 612, 618
        }
    }
}
